alan-turing-institute/AutSPACEs

- server/apps/main/templates/main/my_stories.html
- server/apps/main/urls.py
- server/apps/main/views.py
- server/settings/environments/development.py
Such an amazing experience! Successfully created my stories page, had to expose localhost:80 to ngrok, and include the ngrok HTTPS address to open humans. 😃
> Created "My stories" MVP page #19

- server/apps/main/templates/main/share_experiences.html
- server/apps/main/views.py
Here, I added the file and changed the views accordingly. Experiences can also be entered in the page and will be saved in the local database. Right now, only the tags for the 1st and 3rd option work i.e. public and research.
> Added Share experiences file

- server/apps/main/templates/main/confirmation_page.html
- server/apps/main/urls.py
- server/apps/main/views.py
- server/settings/components/common.py
@jhlink I'm done working on #121, could you please review my code and let me know if there's anything I should change? Thank you!
> Created "Confirmation - Navigation Screen" page

- server/apps/main/templates/main/my_stories.html
- server/apps/main/views.py
pull request for issue https://github.com/alan-turing-institute/AutSPACEs/issues/136
> Navigation: Standardize My Stories page nav bar

- server/apps/main/templates/main/moderate_public_experiences.html
- server/apps/main/views.py
Pull request for issue https://github.com/alan-turing-institute/AutSPACEs/issues/137
> Navigation: Standardize Moderation page nav bar

- server/apps/main/templates/main/experiences_page.html
Pull request for issue ref https://github.com/alan-turing-institute/AutSPACEs/issues/154
> change ice cream experience text from view experience

- server/apps/main/templates/css/home.css
- server/apps/main/templates/main/about_us.html
- server/apps/main/templates/main/confirmation_page.html
- server/apps/main/templates/main/experiences_page.html
- server/apps/main/templates/main/home.html
- server/apps/main/templates/main/moderate_public_experiences.html
- server/apps/main/templates/main/my_stories.html
- server/apps/main/templates/main/share_experiences.html
- server/apps/main/templates/main/what_autism_is.html
- server/apps/main/urls.py
- server/apps/main/views.py
- changed all bootstrap version to 4.0 #184 
- added toggler view for the navigation bar #176
> Unified bootstrap to 4.0

- platform-code/about-page/README.md
- platform-code/crisis-support-page/README.md
- platform-code/enter-experiences-flow/README.md
- platform-code/home-page/README.md
- platform-code/moderation-flow/README.md
- platform-code/settings-page/README.md
- platform-code/sign-in/README.md
- platform-code/sign-up-flow/README.md
- platform-code/view-other-experiences-page/README.md
- platform-code/view-own-experiences-page/README.md
This folder is confusing as the platform code is not held here. This PR deletes the empty "platform code" folders.
> Delete platform-code directory

- README.md
> Add server info

- server/apps/main/views.py
> only show approved experiences publicly

- server/apps/main/templates/main/my_stories.html
- server/apps/main/views.py
- server/settings/components/common.py
Alternative approach to date time formatting suggested by @gedankenstuecke in PR #437
Original:
> 2023-01-30T15:40:39.857995Z
Humanized:
> 4 days, 18 hours ago
> Humanise datetime

- server/apps/main/templates/main/experiences_page.html
- server/apps/main/views.py
Implementation of a search function to return (case insensitive) matches to the search from moderated stories title, experience, or suggestion
Uses GET (instead of POST)
Filters triggering stories if checkbox ticked
> Implement stories search bar

- 00-project-documentation/moderation/README.md
- 00-project-documentation/moderation/moderation-decisions.md
- 00-project-documentation/moderation/moderation-review-guidelines.md
- 00-project-documentation/moderation/moderator-guidelines.md
This adds the important moderation files around decisions themselves to the project management folder. These files are the last ones that were needed to finish the file transfer. 
Closes #260, and imho realistically closes the whole Repo refresh milestone.
> add moderation files

- server/apps/main/forms.py
- server/apps/main/templates/main/moderate_experience.html
- server/apps/main/templates/main/moderate_public_experiences.html
- server/apps/main/templates/main/share_experiences.html
- server/apps/main/views.py
The moderation view now is a custom template instead of re-using the existing write/edit template. Beyond for allowing for a more customized view generally, I also added a display of the edit history that @helendduncan wrote in #448!
> Make separate moderation view

- config/.env.template
- dev_readme.md
- docker-run.sh
- docker/django/Dockerfile
This change incorporates Helen's poetry update changes and adds some additional comments for the benefit of users running with M1 macs.
I've tested this on an M1 mac and on an x64 Linux machine and it worked fine on both, but I've not been able to test it on Windows.
> Poetry update

- .coveragerc
- .github/workflows/continuous_integration.yml
- .github/workflows/coverage.yml
- poetry.lock
- pyproject.toml
This PR slightly restructures our GH actions: 
It now runs the test while also creating the coverage report for the tests. Finishing the tests triggers a second task, which leads to a comment of the test coverage being added to the PR, c.f. https://github.com/gedankenstuecke/AutSPACEs/pull/1 for an example.
> Run action for displaying test coverage on PR

- server/apps/main/tests/fixtures/moderate_experience.yaml
- server/apps/main/tests/test_moderate_views.py
- server/apps/main/views.py
- server/settings/environments/development.py
> Test moderation views

- server/apps/main/templates/main/code_of_conduct.html
- server/apps/main/templates/main/help.html
- server/apps/main/templates/main/partials/navigation.html
- server/apps/main/urls.py
- server/apps/main/views.py
Per the co-working with @GeorgiaHCA the "What is Autism" page has been copied (and slightly modified) to make space for the Code of Conduct and Help pages
> Add Code of Conduct and Help pages (placeholder)

- server/apps/main/templates/main/application.html
- server/apps/main/templates/main/my_stories.html
- server/apps/main/templates/main/story_table.html
- server/apps/main/templatetags/story_filters.py
- server/apps/main/tests/test_story_filters.py
- static/css/main.css
"My stories" is split into three tabs: Public / In Review / Private, with stories filtered accordingly
This is only one possible way to categorise stories, so it would be good to get opinions on this! 
Fixes #464
> Better overview for the "My Stories" page

- server/apps/main/templates/main/partials/navigation.html
- static/css/main.css
This PR closes #489 by correctly formatting the navigation bar. I've also cleaned up the custom CSS for things that became unused due correctly applying the Bootstrap classes now. 
@helendduncan @llewelld @mastoffel I don't know who of you has capacities for reviewing, so whoever has some time, please feel free to have a look 😄
> fix navbar spacing

- dev_readme.md
I did some minor work on the dev readme file: 
1. Restructure the how-to part, using correct heading levels
2. Add instructions on accessing the Django shell
3. Add instructions on making a superuser account
4. Add instructions on adding a user to moderators
> Update dev readme 

- server/apps/main/templates/main/experiences_page.html
- server/apps/main/templates/main/moderate_experience.html
- server/apps/main/templates/main/single_story.html
- server/apps/main/tests/test_views.py
- server/apps/main/urls.py
- server/apps/main/views.py
Closes #498 
Single story page with formatting similar to the moderation page
As well as feedback on technical features - any feedback/edits about layout greatly appreciated
> Single story view option

- server/apps/users/forms.py
- server/apps/users/helpers.py
- server/apps/users/templates/users/delete.html
- server/apps/users/templates/users/goodbye.html
- server/apps/users/templates/users/profile.html
- server/apps/users/tests/fixtures/delete_user.yaml
- server/apps/users/tests/test_views.py
- server/apps/users/urls.py
- server/apps/users/views.py
- static/css/main.css
Adds an option to delete the user's account to the profile page.
> Add an account deletion option

- server/apps/main/templates/main/partials/navigation.html
- server/apps/main/tests/test_moderate_views.py
- server/apps/main/tests/test_views.py
- server/apps/main/urls.py
- server/apps/main/views.py
- server/apps/users/tests/test_views.py
> Decide on single entry page

- server/apps/users/helpers.py
> send explicit deauth if not default

- server/apps/main/templates/main/experiences_page.html
- server/apps/main/templates/main/partials/navigation.html
Changes the structure of the navigation menu bar at the top of every page, following feedback from user testing.
Contributes to #592.
> Rearrange the navbar

- server/apps/main/helpers.py
- server/apps/main/templates/main/moderation_list.html
- server/apps/main/templates/main/moderation_table.html
- server/apps/main/templates/main/partials/navigation.html
- server/apps/main/views.py
- static/css/main.css
- static/js/store-tab.js
Switches the three moderation pages (pending, approved, rejected) to use tabs on a single page.
Contributes to #592.
> Switch moderation pages to use tabs

- server/apps/main/templates/main/partials/navigation.html
- static/css/main.css
Addresses & closes missing bit of #592
> fix navbar dropdown

- server/apps/main/templates/main/partials/navigation.html
fixes problem introduced in #629
> fix accidental duplicate

- server/apps/main/templates/main/experiences_page.html
- server/apps/main/templates/main/help.html
- server/apps/main/templates/main/home.html
- server/apps/main/templates/main/partials/navigation.html
- server/apps/main/templates/main/registration.html
- server/apps/main/templates/main/what_autism_is.html
- server/apps/main/tests/test_views.py
- server/apps/main/views.py
- server/apps/users/tests/test_views.py
- static/css/main.css
- static/js/jquery.connections.js
- static/js/registration-connections.js
Adds "Add Story" buttons to various places.
Adds a process diagram to the registration page to try to clarify what the user needs to do to register an accont.
Fixes #599.
> Make it easier to add a story

- server/apps/main/templates/main/moderate_experience.html
- server/apps/main/templates/main/share_experiences.html
@GeorgiaHCA and I discovered that those buttons were still not linked and we'd like those to work for the demo with Autistica on Thursday! :D
> fix button links in accordion on share

- server/apps/main/templates/main/moderate_experience.html
- server/apps/main/templates/main/share_experiences.html
- static/js/set_relationship_vis.js
This closes #607, which is part of the usability improvements 🙂
> add checkbox to "other" trigger

- server/apps/main/templates/main/single_story.html
> fix display self-id for single story

- server/apps/main/templates/main/participant_information.html
- server/apps/main/templates/main/registration.html
This PR closes #682, by including the updated participant information sheet on the webpage
> updated PIS

- Dockerfile
- config/sshd_config
- docker/django/gunicorn.sh
With these changes it so far still crashes, with the log output below: 
```
2024-05-28T15:49:30.2888559Z 03.49.30.268543
2024-05-28T15:54:58.3641253Z Exception Message : The operation was canceled.
2024-05-28T15:54:58.3944131Z Exception StackTrace :    at System.Net.Http.HttpClient.HandleFailure(Exception , Boolean , HttpResponseMessage , CancellationTokenSource , CancellationToken , CancellationTokenSource )
2024-05-28T15:54:58.3962907Z    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
2024-05-28T15:54:58.3963266Z    at Microsoft.AspNetCore.Proxy.ProxyMiddleware.Invoke(HttpContext context)
2024-05-28T15:54:58.3963440Z    at …
```
> try azure's ssh for container access

- server/apps/main/forms.py
- server/apps/main/templates/main/about_us.html
- server/apps/main/templates/main/content_moderation_guidelines.html
- server/apps/main/templates/main/experiences_page.html
- server/apps/main/templates/main/help.html
- server/apps/main/templates/main/home.html
- server/apps/main/templates/main/moderate_experience.html
- server/apps/main/templates/main/moderation_table.html
- server/apps/main/templates/main/my_stories.html
- server/apps/main/templates/main/partials/footer.html
- server/apps/main/templates/main/partials/navigation.html
- server/apps/main/templates/main/participant_information.html
- server/apps/main/templates/main/registration.html
- server/apps/main/templates/main/share_experiences.html
- server/apps/main/templates/main/single_story.html
- server/apps/main/templates/main/story_table.html
- server/apps/main/templates/main/what_autism_is.html
- server/apps/users/forms.py
- server/apps/users/templates/users/profile.html
Pages/sections done: 
- nav bar
- front page
- footer
- registration page 
- share experience
- fixed capitalisation in trigger labels
- experience list page
- my stories page
- "about autism" page
> Add in copy edits
