docker-compose.override.yml, docker-compose.yml
see https://github.com/docker/compose-cli/issues/1896 to fix issue with Docker Compose version v2.0.0-beta.6
=> removed comments in .yml files causing a docker compose error

dev_readme.md
Some contributors have been unable to build on amd64 machines. This fixed the issue in my case, hopefully it works for everyone else too.
=> Add instruction for M1 processors to dev readme

server/apps/main/templates/main/my_stories.html
This commit successfully passes the necessary form fields to the view `share_experience`, when you click the `Edit` button. 
The `share_experience` view automatically prepopulates the form - this works well.
The next step is to amend the form to have a hidden `file.id` field that we can check for when `edit=False` to determine whether 'this is a form submission of an edited form'.
=> correct passing of data to share_experience

server/apps/main/forms.py, server/apps/main/templates/main/share_experiences.html
In [this discussion](https://github.com/alan-turing-institute/AutSPACEs/pull/394#discussion_r1045807012) it was suggested to keep a checkbox alongside `Other`, since when you type in `Other` the placeholder disappears.
The simplest solution is to attach an `Other` label, which I have done in this commit. Keeping the checkbox and textbox in sync (e.g. automatic typing enables the checkbox) requires Javascript. Though this is probably simple enough to implement, it would take longer than the few mins dedicated to this solution. I thought it was good enough for now, in order to prioritise other developments towards the MVP.
=> add other label and left alignment

server/apps/main/forms.py, server/apps/main/templates/main/deletion_confirmation.html, server/apps/main/templates/main/deletion_success.html, server/apps/main/templates/main/my_stories.html, server/apps/main/templates/main/share_experiences.html, server/apps/main/urls.py, server/apps/main/views.py
Closes #411.
A few changes limit the amount of POST requests:
Url parameters:
- `delete_exp` takes a uuid and title. 
- `edit_exp` takes a uuid. 
- There is a new helper function, `get_oh_file()`, that, given a uuid, retrieves the file data.
`delete_exp` and `edit_exp` are called as GET requests from the `my_stories` tab (see description in #411).
`POST` requests are only executed when data is to be changed:
- on deletion.
- on submission (of new or edited experience). 
I have also deleted the now-redundant hidden form field `uuid`.
Comments for the future:
- the url passed to `delete_exp` could be very long since it includes the title. It might be nice to do the confirmation on the same page, with javascript, rather than have separate confirmation and success pages.
=> Remove unnecessary POST request to GET request

server/apps/main/forms.py, server/apps/main/templates/main/moderate_public_experiences.html, server/apps/main/templates/main/my_stories.html, server/apps/main/templates/main/share_experiences.html, server/apps/main/urls.py, server/apps/main/views.py
PR to address tasks raised in #162. Copied below for information:
> ### Tasks
> - [x] Populate a table of experiences, tagged with "review"
> - [x] Add an approve button that sets the moderation state of the experience to "Accepted/Approved/Public"
> - [x] Add a reject button that sets the moderation state of the experience to "Rejected"
moderate_public_experiences has been updated to receive both un-moderated and moderated experiences from the (local) database of PublicExperience objects.
Moderators can access either by clicking on the accordion link and getting a list of the relevant experiences.
The "moderate new experience" or "review moderated experience" buttons take the moderators back to the shared_experiences form as a user would see if they were editing their own experience. …
=> Implement moderation page

server/apps/main/templates/main/partials/navigation.html, server/apps/main/templatetags/custom_tags.py, server/apps/main/views.py
Addressing issue #166 copied below
> ## Description
> User roles/permissions will be managed through the Django admin panel. An admin by default will be able to view, manipulate, and remove all data and users. However, the primary utility for feature will be assigning which users are moderators. 
> 
> ### Tasks
> Users use their OpenHumans credentials to utilize the site. 
> - [x] Create a new or use the pre-existing users table, provided in the Django admin library, and create a foreign key on the OpenHumans user ID
> - [x] Create a Moderator status
> - [x] Allow admin to set a user as moderator
> - [x] Allow admin to set a moderator as a user
> - [ ] Add documentation on how to create an admin user for development
Custom template tag to limit permissions based on user status (see below)
=> Set up Admin pages and permissions

server/apps/main/views.py
The statuses dictionary was being overwritten by the counting of the moderated stories - inelegant counting method fixes this
=> Change moderation count so not to overwite statuses

server/apps/main/forms.py, server/apps/main/templates/main/my_stories.html, server/apps/main/views.py
I have changed the field names in `ShareExperienceForm` to match those in our `PublicExperience` model.
This means that we can much more concisely map from one to the other.
I have kept the form as a `Form` rather than a `ModelForm`, since this would require unnecessary refactoring without much gain in conciseness or understanding, I think.
=> Align model and form

server/apps/main/templates/main/share_experiences.html, server/apps/main/views.py
This closes  #445 
I noticed that it was only the passing of the `uuid` to the creation method that was missing to allow the moderation to work as expected. The second change was to then remove the potentially duplicate UUID that would be present when editing existing experiences.
=> Store UUID in public experiences correctly

server/apps/main/views.py
Closes issue #447 
Replaced `process_enabled_form_keys` with `process_trigger_warnings`.
Uses the newly produced `ModerateExperience` form. 
Form is sent to the function and cleaned, list of trigger warnings is given to it and any that are absent are filled as false.
Story details extracted in separate function and merged into a data dictionary that is sent to `update_public_experience_db`
=> Ensure changes to trigger warnings made during moderation persist

server/apps/main/helpers.py, server/apps/main/tests/fixtures/get_oh_combined.yaml, server/apps/main/tests/fixtures/get_oh_file.yaml, server/apps/main/tests/test_helpers.py, server/apps/main/views.py, server/settings/components/common.py
Fixes #468.
There was considerable overlap between the metadata and the file contents stored on OpenHuman. This change streamlines the metadata to remove the descriptive text. The descriptive text is now retrieved by downloading the file from OpenHuman instead.
=> Cleanup metadata stored on OpenHuman

server/apps/main/templates/main/help.html
Populate the help page with content from the [GoogleDocs](https://docs.google.com/document/d/106Ma7lEWZksRf58UCP8XFNjlivMQXz2yQCrcNEbxyTQ/edit#) description. 
Only change to the text is to specify that stories are stored in OpenHumans
Contributes to issue #460 but does not complete it
=> Populate help page

server/apps/main/forms.py, server/apps/main/templates/main/application.html, server/apps/main/templates/main/share_experiences.html, server/apps/main/views.py, static/js/submit-warning.js
* Adds warning popup modal when viewable stories get edited again.   
* Tracks the "Share on AutSPACE website" tickbox, so that unchecking the box during editing prevents the popup from showing up (as there won't be a second moderation). 
Issue #433
=> Add warning popup when editing resets the moderation pipeline.

server/apps/main/templates/main/code_of_conduct.html, static/css/main.css
Adds initial (not-yet-complete) text for the Code of Conduct page.
Contributes to #460.
The text used for this is from the [Code of Conduct copy doc](https://docs.google.com/document/d/1qhBlUxMVv8F_QGuY1re2xbLLZ-mNmak4TISmC-nFW58/edit#).
=> Add Code of Conduct initial content

server/apps/main/forms.py, server/apps/main/helpers.py, server/apps/main/templates/main/moderate_experience.html, server/apps/main/templates/main/moderation_list.html, server/apps/main/templates/main/partials/navigation.html, server/apps/main/tests/test_helpers.py, server/apps/main/tests/test_moderate_views.py, server/apps/main/urls.py, server/apps/main/views.py, server/settings/components/common.py
Restructures the moderation pages:
1. Splits the moderation view into three pages: pending, approved and rejected
2. Adds pagination for each of the categories
3. Adds search functionality
Fixes #463.
=> Restructure moderation pages

server/apps/main/templates/main/confirmation_page.html, server/apps/main/templates/main/deletion_success.html
On the post-experience-submission confirmation page there's a number of buttons for next steps. These were somehow weirdly nested between `<a href>` and `<button>` stylings, making them appear slightly strange and less accessible through keyboard navigation (e.g. via `vimium`). 
I've just gone ahead and fixed it :D
=> fix button declarations

server/apps/main/templates/main/share_experiences.html, server/apps/main/views.py
Thanks to @mastoffel's feedback on #512 I had a look over the `share_experience` view and template and fixed some more minor things: 
1. I removed the unused `viewable` variable that was passed on into the template but wasn't used anywhere
2. There was another minor bug in which the `<label for="field_id"/>` didn't work for the public sharing option, due to it being a custom declaration to make @mastoffel's excellent JS work more nicely. I've fixed that and also unified using the right label throughout the template to avoid future issues.
=> Clean experience submission view/template

config/.env.actions, config/.env.template, server/apps/main/helpers.py, server/apps/main/mod_message.txt, server/apps/main/tests/test_helpers.py, server/apps/main/tests/test_moderate_views.py, server/apps/main/views.py
Adds the functionality to send messages to the user when the moderation of their stories change. This relies on the option being enabled in their profile.
The 'mod_message.txt' file contains the text of the message. It has some formatting requirements:
1. The first line is the subject line.
2. All subsequent lines will form the message body.
3. {story}, {profile}, {title} and {status} will be replaced with the URL of the story, the URL of the user's profile, the story title and the new moderation status of the story respectively.
=> Support sending of moderation messages

poetry.lock
Closes #548. 
@llewelld This was generated by just running `poetry lock` from the root directory (but requires having pyenv + poetry set up locally to match versions etc).
=> upgrade packages

server/apps/main/forms.py, server/apps/main/helpers.py, server/apps/main/templates/main/moderate_experience.html, server/apps/main/tests/test_helpers.py, server/apps/main/tests/test_moderate_views.py, server/apps/main/views.py, server/apps/users/helpers.py, static/css/main.css, static/js/moderation-dialogue.js, static/js/moderation-replies.js
Under certain circumstances it may not make sense to submit a review:
1. If the story is being rejected without a reason.
2. If the status is being set to 'not reviewed' but has review comments.
This change adds a dialogue box to warn the user in the case of 1, and block the user in the case of 2.
Fixes #525.
=> Add warning dialogues to moderation page

server/apps/main/tests/test_views.py, server/apps/main/views.py, server/apps/users/views.py
The get_user_profile helper function will return None of the user profile doesn't exist, rather than triggering an exception. These changes switch to using the helper function to avoid potentially errors iif the user isn't logged in.
Also adds a unit test to catch the error case.
Fixes #552.
=> Use get_user_profile to get the UserProfile object

server/apps/main/helpers.py, server/apps/main/templates/main/deletion_confirmation.html, server/apps/main/templates/main/story_table.html, server/apps/main/tests/test_views.py, server/apps/main/urls.py, server/apps/main/views.py
This PR addresses a `TODO` item that was left in the code: 
Trying to delete an experience takes a user from the list view to a new confirmation page. On that page we want to display the title of the experience without having to query Open Humans again. So far this is achieved by passing the experience title as a URL parameter: 
`path("delete/<uuid>/<title>/", views.delete_experience, name="delete_exp"),`
This is a bit clunky and could potentially break depending on the characters people use in their titles etc (though we did some proper character escaping). 
A better solution is to store these titles somewhere locally in somewhat ephemeral storage. Django provides a `session` backend for such purposes and we already use that middleware implicitly without actually making use of it. In our …
=> Use sessions for storing experience title

server/settings/environments/development.py
Currently, the admin backend in development gives the above error when trying to look at the UserProfile admin pages. This is because it loops over all `UserProfile`s which in turn lazy-loads the `user.username` from the database, c.f. users.models:
```
def __str__(self):
return "Profile for {}".format(self.user.username)
```
These added requests are mainly due to how the admin backend works in presenting & loading this data and I don't think we use the `str` method anywhere else (otherwise we'd already have stumbled over those errors). 
Given this, I just added it to the whitelist, for the nplusone library to not check for this any more (as it's only for performance monitoring)
=> fix nplusone whitelist

server/apps/main/templates/main/moderate_experience.html, server/apps/main/templates/main/partials/template_moderation_dropdown.html, server/apps/main/templates/main/partials/template_moderation_warnings.html
Closes #553. 
This cleans up the `moderate_experience.html` template a bit by moving the template information used by the JS into its own separate partials.
=> move templates to partials

Dockerfile, dev_readme.md, fly.toml, poetry.lock, pyproject.toml, server/settings/components/common.py
This PR tweaks our config slightly and adds the files necessary to deploy a test environment to fly.io to allow participants in the user testing to explore the website without having to share remote control via zoom. 
It adds/changes: 
1. The `Dockerfile` used for the fly.io deployment 
2. The `fly.toml` for the config on their end
3. The `dj-database-url` package which loads the postgres database from the `DATABASE_URL` environment variable that fly uses
4. edits the `common.py` config to detect if a `DATABASE_URL` is set in order to identify that we're on fly.io to then use that config rather than the local dev setup.
=> Add configs for user test deployment to fly.io

fly.toml, server/apps/main/management/commands/seed_db.py, server/apps/main/tests/test_management_commands.py, server/settings/environments/development.py, server/settings/environments/production.py
This PR expands the seeding a bit for the upcoming user testing: 
1. Instead of trying to expand on any existing data, the management command now first deletes all `OpenHumansMember` and `PublicExperience` objects in the database. This is relevant for restoring the DB back to the "default" for user testing
2. The `seed_db` command is now covered by tests
3. I noticed that I had forgotten to uncomment the release stage in the fly.io deployment, which was necessary to make it migrate the DB following @helendduncan's authorship improvements!
=> Expand seed management cmd 4 user testing

server/apps/main/management/commands/seed_db.py, server/apps/main/management/commands/unseed_db.py, server/apps/main/tests/test_management_commands.py, server/settings/environments/development.py
closes #584 
Management command to delete the user and their OH data and then remove the seeded stories from the DB
Edited `seed_db.py` to remove its analogous functions.
=> User Testing: Restore DB to initial conditions

server/apps/main/templates/main/about_us.html, server/apps/main/templates/main/code_of_conduct.html, server/apps/main/templates/main/help.html, server/apps/main/templates/main/what_autism_is.html, static/css/main.css, static/js/menu-alignment.js
When the width of the viewport is reduced below 992 pixels the menu along the left hand edge overlaps the text on the page. Using Bootstraps columns it should jump above the text, but this is prevented because the positioning of the menu is set to fixed (so that it stays on screen when the page is scrolled).
This change fixes this by creating a media selector that makes the menu position relative when the width of the page reduces below 992 pixels. An invisible column is also added to avoid the need to place the menu inside another column, and to prevent the text from shifting to the left when the menu position is set to fixed.
The footer position is also set to relative so that it goes over (rather than under) the menu to avoids a nasty overlap when viewport height is small.
Contributes …
=> Avoid help page menu overlapping text

server/apps/main/carousel.json, server/apps/main/helpers.py, server/apps/main/templates/main/home.html, server/apps/main/templates/main/partials/footer.html, server/apps/main/templates/main/single_story.html, server/apps/main/tests/carousel-test01.json, server/apps/main/tests/carousel-test02.json, server/apps/main/tests/carousel-test03.json, server/apps/main/tests/carousel-test04.json, server/apps/main/tests/test_helpers.py, server/apps/main/tests/test_views.py, server/apps/main/views.py, static/css/main.css
Updates te homepage layout and content following user testing and so that all of the elements work correctk (e.g. links to other parts of the site).
Contributes to #586.
=> Restructure home page

server/apps/main/templates/main/about_us.html, server/apps/main/templates/main/application.html, server/apps/main/templates/main/code_of_conduct.html, server/apps/main/templates/main/experiences_page.html, server/apps/main/templates/main/help.html, server/apps/main/templates/main/home.html, server/apps/main/templates/main/moderate_experience.html, server/apps/main/templates/main/moderate_public_experiences.html, server/apps/main/templates/main/moderation_list.html, server/apps/main/templates/main/moderation_table.html, server/apps/main/templates/main/my_stories.html, server/apps/main/templates/main/partials/jquery.html, server/apps/main/templates/main/partials/navigation.html, server/apps/main/templates/main/partials/template_moderation_dropdown.html, server/apps/main/templates/main/registration.html, server/apps/main/templates/main/share_experiences.html, server/apps/main/templates/main/single_story.html, server/apps/main/templates/main/story_table.html, server/apps/main/templates/main/what_autism_is.html, server/apps/users/forms.py, server/apps/users/templates/users/delete.html, server/apps/users/templates/users/profile.html, static/css/main.css, static/js/main.js, static/js/shared-stories-filtering.js, static/js/store-tab.js
This will potentially be a bit of work as a lot of declarations have changed, but it would be good to migrate now rather than later in order to avoid being too outdated. This will also help with a lot of the accessibility improvements identified during the user tests (e.g. #605 & #603).
=> Migrate to Bootstrap 5x

server/apps/main/templates/main/moderate_experience.html, server/apps/main/templates/main/share_experiences.html
Fixes the CoC accordion texts to be not misleading on what is acceptable/not acceptable. See screenshots below
=> update text on "read before"

server/apps/main/templates/main/about_us.html, server/apps/main/templates/main/confirmation_page.html, server/apps/main/templates/main/content_moderation_guidelines.html, server/apps/main/templates/main/help.html, server/apps/main/templates/main/moderate_experience.html, server/apps/main/templates/main/partials/footer.html, server/apps/main/templates/main/partials/navigation.html, server/apps/main/templates/main/participant_information.html, server/apps/main/templates/main/share_experiences.html, server/apps/main/tests/test_views.py, server/apps/main/urls.py, server/apps/main/views.py, static/css/main.css, static/js/moderation-replies.js
This PR adds the Participant Information Sheet, which we have also submitted as a PDF version for the ethics submission as a proper page to the AutSPACEs platform. 
As part of this work, I have also renamed and clarified the two types of "Code of Conduct" we have so far used interchangeably: 
1. The "actual" code of conduct ([on GH here](https://github.com/alan-turing-institute/AutSPACEs/blob/main/code-of-conduct.md)), which covers the interactions in Slack, Zoom, etc. 
2. The "content moderation guidelines" that moderators use to evaluate publicly shared stories and moderate them. 
So far the latter was also called "code of conduct", leading to confusion as there were two different documents with the same name. For clarity (and in line with the wording we've used for the moderation …
=> Adding Participant Information + clarify CoC vs content moderation

server/apps/main/templates/main/experiences_page.html, static/js/shared-stories-filtering.js
This fixes #606, by including a modal overlay of a "spinner" to indicate that the updated results are loaded. 
Technically, this is a bit smoke & mirrors, as it's completely unrelated to the actual loading, instead there's a quarter second period in which the overlay is shown before then reloading the website with the new results. 
While definitely not an elegant solution, I think for now this is a pragmatic approach, as the more dynamic implementation would mean a quite big chunk of work to refactor how the loading of the results happens!
=> Indicate that trigger-toggles worked

server/apps/users/templates/users/profile.html
This closes #612 by providing a clearer labeling of what those toggle switchees do (and that they can be overwritten/changed)
=> Clarify trigger defaults on profile page

server/apps/main/templates/main/single_story.html
To move back from a single story to "correct" page of public experiences, with triggers etc preserved, closes #540 540
In the end it didn't require messing around with custom sessions, as Django helpfully offers the `META.HTTP_REFERER` entry in the `request` itself!
=> add contextual back button

server/apps/main/feeds.py, server/apps/main/templates/main/application.html, server/apps/main/templates/main/experiences_page.html, server/apps/main/templates/main/feed.html, server/apps/main/tests/test_views.py, server/apps/main/urls.py, server/apps/main/views.py
Closes #610 
This PR adds both an Atom & RSS feed on the public experiences page, properly linked behind the scenes in the `head` of the website as appropriate to facilitate automatic discovery of it. 
It also includes a link to the feed on that page in order to highlight this flag beyond automated discovery. Furthermore, the feed links automatically mirror the current view including the trigger inclusion choices, so that people can subscribe to a feed that includes only those topics they are comfortable reading about.
=> adds rss/atom feeds for public experiences

server/apps/main/helpers.py, server/apps/main/templates/main/moderate_experience.html, server/apps/main/templates/main/share_experiences.html, static/css/main.css
This PR fixes #661, which @GeorgiaHCA & I uncovered in the second round of (ongoing) user testing. 
While doing this I found two more bugs that this PR addresses: 
1. The text in the "moderation history" table in the moderate view was black & black as well when using dark mode
2. The moderation form crashed when using the "other trigger labels" field, due to how the checkbox/trigger labels were processed.
=> Fix dark buttons & "other" trigger moderation bug

server/apps/main/forms.py, server/apps/main/templates/main/home.html, server/apps/main/templates/main/partials/footer.html, server/apps/main/templates/main/share_experiences.html, server/apps/users/forms.py, server/apps/users/templates/users/delete.html, server/apps/users/templates/users/profile.html, static/css/main.css, static/js/shared-stories-filtering.js
=> [WIP] lower visual noise

server/apps/main/helpers.py, server/apps/main/templates/main/moderation_table.html, server/apps/main/templates/main/share_experiences.html
This closes #511 (for now at least) by adding in a small label that highlights on the moderation panel when a given story is someone's first contribution (see screenshot).
=> Mark 1st time contributions
